#!/usr/bin/env python3

import sys
from subprocess import call
from subprocess import Popen
import subprocess


def main (asm_file):
    exit_code = call (["assembler", asm_file])
    if (exit_code > 0):
        exit (1)

    call (["vm", "out.exec"])
    call (["rm", "out.exec"])


if __name__ == '__main__':
    if (len (sys.argv) < 2):
        print ("usage: cs4974 assembly_file")
        exit (1)

    main (sys.argv[1])

